create input and login
Squad1-BTI/frontend-login pull request #2
Opened 2024-09-06 12:47 UTC by Bruno-Meireles

2024-09-08 20:02 UTC, RO-HSA requested changes
Dá uma olhada nos comentários que eu deixei e faz as alterações necessárias

2024-09-08 20:02 UTC, RO-HSA commented on src/app/login.tsx
> + export default  function Login() {
Não precisamos da página de login neste momento, apenas o input

2024-09-08 20:02 UTC, RO-HSA commented on src/app/page.tsx
> +        <Login></Login>
Não precisamos da página de login neste momento, apenas o input

2024-09-08 20:02 UTC, RO-HSA commented on src/components/input.tsx
> + export default  function Input() {
O component de input deve retornar apenas a tag input

2024-09-09 09:44 UTC, RO-HSA commented on src/components/UI/input.tsx
> +    const [showPassword, setShowPassword] = React.useState(true); // Estado para controlar a exibição de senha
Favor remover comentários, não é necessário explicar o que é autoexplicativo.

2024-09-09 09:57 UTC, RO-HSA requested changes

2024-09-09 09:57 UTC, RO-HSA commented on src/components/UI/input.tsx
> +      setShowPassword((prevState) => !prevState); // Alterna o estado de exibição
Favor remover comentários, não é necessário explicar o que é autoexplicativo.

2024-09-09 09:57 UTC, RO-HSA commented on src/components/UI/input.tsx
> +  togglePassword?: boolean; // Habilita o modo de alternância de senha
Favor remover comentários, não é necessário explicar o que é autoexplicativo.

2024-09-09 09:57 UTC, RO-HSA commented on src/components/UI/input.tsx
> +const inputVariants = cva(
O estilo do input não está de acordo com o Figma.

2024-09-09 09:57 UTC, RO-HSA commented on src/components/UI/input.tsx
> +export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement>, VariantProps<typeof inputVariants> {
Está dando erro de types. o inputVariants aparentemente possui propriedades que não são compatíveis com o InputHTMLAttributes. Recomendo evitar copiar código por copiar. Dá uma olhada nas documentações também: https://cva.style/docs

2024-09-09 12:47 UTC, migmoroni commented on src/components/UI/input.tsx
> +const inputVariants = cva(
O problema esta em descobrir onde encontrar esse estilo usado

2024-09-09 12:51 UTC, migmoroni commented on src/components/UI/input.tsx
> +export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement>, VariantProps<typeof inputVariants> {
Usei o chatgpt para resolvermos mais rapido. Eu concordo com aprender a usar certinho, não gosto de ficar copiando e quando faço, tento entender o que ocorre. No entanto, se for sem copiar, sugiro pedirmos mais um alongamento de prazo.

2024-09-12 20:29 UTC, RO-HSA requested changes
Corrige só a aparência do input, e já podemos finalizar esse PR.

2024-09-12 20:29 UTC, RO-HSA commented on src/components/UI/input.tsx
> +        default: 'text-gray-800 peer block w-full border-2 px-3 py-2 focus:outline-none focus:ring-2 placeholder:text-sm',
O estilo ainda está diferente do Figma.

2024-09-12 22:30 UTC, RO-HSA approved these changes
LGMT

2024-09-12 22:30 UTC, merged